checks:

  include: [ ]

  exclude: 
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "env-var-secret"
    - "liveness-port"
    - "readiness-port"
    - "startup-port"
    - "non-existent-service-account"
    - "latest-tag"
