kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ns.yaml
  - proxy

images:
  # workspace-manager
  - name: quay.io/konflux-ci/workspace-manager
    digest: sha256:d61c162713e3dc288bd835bde11ff18924e69223903e8eb4a777110e542b3f2b
  - name: quay.io/konflux-ci/konflux-ui
    digest: sha256:2451fc00f718c4c23a2db33eeb8e5d5033d08219f1ee21052bbb6f911af1d50e

namespace: konflux-ui
