apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:e9af7bb94ebe811540dda35370d3312f871a6b94cf64f6c86fdf6f5237cdfc26
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:874004cf73755634c8d70ad98884b3e8aecd0fe8fb375b1810819f4f58af9041
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:e7554f912752ce0751ae7917bb51acbe64779e4f741d7fbfda2868cb267800ee
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:d409572b4bc77509ef33fe74393f388aafbdb500cc0971ac4a995a70602aa271
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:b71f7a25fa7ff30ee0e13475ffdfb66c7482c1131a94cdd8f48fdc43a3c354f4
