apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:4ab71e6f644f45712b60b40ae09d7dfc2c60b59e9a24b90a51f4b71e5a41f290
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:2345a041ec82099d3ba9a08eb7c1b22dc00ef6ae775edd7da7747d4046053cbc
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:f62e3412be4d9b62cfb52828c2269dae68b82004aee2282d65f6f217e32d76ec
