apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:7f6b7ef4911a333fd4c668877f9c61c030457bf2db028fea98011653bb2f14d8
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:9d2953688a3ecccd7760e1ce13f58ddd57c5e816e3ae6a7c3c84686ab719f2d3
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:b3f398fe7077fcf41aea5169d9820ff119fa98fb117424fff960794043108457
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:bd860086241db3e9026c78dd50ff3daa0470eeff9c369f3b24a5309d80fc7c85
