apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:1e2fd5c77b8ea7542fc4e40dfb49bbbcc1739ebb0786e399935a6260406e56c2
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:625a9405f32d1e177028505c0df208f0f1a282d5ae0332fdc78163443487f980
