apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:61aab0f5b017c9c0e9b1ed01857cdc8b901b2e9b64135c767d0beaf6ab613154
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:e6569bee481c06b56624f69a8c7df1b869698484dc9eacf2367938237e7653c0
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:e21004c007dcc7514198879f1d1579d79e06a19949e26c694b9daa64b9c14857
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:bb5e654f2e6e909cf30d65ffc1b07c89a399130bb5e5f6184fcf9afc5355d6b0
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:d626bfa0376a9c652097fa62c789b9357c58a99c39d65a70019fea5416f9ebbd
