apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:05baa1e522718b10c3726e8206936b4673d3b70a36d22a6f3dabbc7a312b14d4
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:3cc0114c3299f6c0a4cc7a9112950c77a0547bc5ef4a1daaa576a2520784930a
