apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:f41554d633a3d7e4c364b394684d772c41913873d7accb87da82cd82a4757e6d
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:65f39c234ead7b847e7f3443223a6b25a4b35828cb2ea34ad6a4976d6a0d1f33
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:3c8374c5fbc8d7d659e6e3d21cb9029f61542df439aa86ed8cf38d014eb5fb34
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:cf84c66b8972c00f804ab8151c2aaeec25f62d65f3c60915da41fc65413ffd8f
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:0377ab6ddbe9e0deb172a83e78918cc0c5bf476dc953ee4887c66a82e2a28f39
