apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:1887dc59fb00435482a1183ca695d0c86c0c8824441ca392e9b6ed2681d6e0a7
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:f9c2ef781e98677ea24efb46b2d11f1219ff5a4bc4633b7094ce58bbb6151b26
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:90d54f43cc6276e11c8f4cabed4cd8cac0efa4f24d476650aff576811000b255
