apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:47cffe1328cf97c660c3a41c22bde2555383a3781e13096d36dae35d0bd0f96f
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:267fff8b121b29a6d59e64857a24fda2a2bb76beaf6177b7bfa93521303bb556
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:18c3b9c0d58d588e4ae9b3208a9a14a7902022bbea20db3de9a1700883ef4145
    - name: tekton-bundle-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder@sha256:1bc5fee806ec9b3d68782d6eb7f4658357dcc843331ca025e077bc83150f32fa
    - name: tekton-bundle-builder-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-tekton-bundle-builder-oci-ta@sha256:4ca4c7dcefec8615b809fa702062b73b4ef65a94a8ebe401eb49040fd2636902
