apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder@sha256:c97934ad71b3307ab42b499976617edb11d1d12624ebaaf13c8ae2ca193ed3cc
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build@sha256:9bfccbd2052e5723e22a3a9eaeed1bfb292a1d8b3fe7da97f939fd7c453c50e7
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:52dbcc048ef9f6c3aa94d9e674f763be3f0c084be6addc12739a99ebc8915d93
